siteName: Kabooly
title: Pay monthly websites | Kabooly
author: David White
url: https://github.com/webdigga/kabooly
poweredBy: Kabooly
description: Pay monthly websites, expertly built by Kabooly. A Pay Monthly Digital service for small business websites & marketing. Everything you need to succeed online.
type: website
email: david@kabooly.com
phoneNumber: "07877304672"
companyNumber: "15653819"
