siteName: Anttz Family Chiropractic
author: David White
poweredBy: Kabooly
poweredByUrl: https://kabooly.com
email: info@anttzchiro.co.uk
phoneNumber: "0208 016 9375"
companyNumber: "12134174"
addressLineOne: Unit 11
addressLineTwo: Canbury Business Park
addressLineThree: Elm Crescent
townCity: Kingston Upon Thames
postCode: KT2 6HJ
locationLatLong: Unit+11,+Canbury+Business+Park,+Elm+Crescent,+Kingston+Upon+Thames,+KT2+6HL
