siteName: Anttz Family Chiropractic
author: David White
poweredBy: Kabooly
poweredByUrl: https://kabooly.com
email: anttzchiro@gmail.com
phoneNumber: "07444079680"
companyNumber: "12134174"
address: Unit 11, Canbury Business Park, Elm Crescent, Kingston Upon Thames, KT2 6HL
locationLatLong: Unit+11,+Canbury+Business+Park,+Elm+Crescent,+Kingston+Upon+Thames,+KT2+6HL
