backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "src/_includes/static/img"
public_folder: "/_includes/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Article"
    name: "articles"
    folder: "src/articles"
    create: true
    editor:
      preview: false
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string",
        hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
      }
      - { 
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
      }
      - {
        label: "Description",
        name: "description",
        widget: "string",
        hint: "*Used in search engines (between 50 and 160 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{50,160}$', "Must be between 50 and 160 characters"]
      }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "type"
        name: "type"
        create: true
        options: ["article", "privacy"]
        default: "article"
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["article", "privacy", "report"]
        default: ["article"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: firstLevelItems
            widget: list
            collapsed: false
            allow_add: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
              - label: Nav Items
                name: secondLevelItems
                widget: list
                collapsed: true
                fields:
                  - { label: Title, name: text, widget: string }
                  - { label: URL, name: url, widget: string }
              
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Site Name, name: siteName, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: Powered by, name: poweredBy, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Phone number, name: phoneNumber, widget: string }
          - { label: Company number, name: companyNumber, widget: string }
  - label: "Components"
    name: "components"
    editor:
      preview: false
    files:
      - label: "Why Anttz"
        name: "whyAnttz"
        file: "src/_data/whyAnttz.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: text }
          - label: "Image"
            name: "image"
            widget: "image"
            choose_url: true
            required: true
            media_library:
              config:
                multiple: false
          - { label: Image alternative text, name: imageAlt, widget: string }
      - label: "Hero"
        name: "hero"
        file: "src/_data/hero.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Title accent text, name: titleAccentText, widget: string }
          - { label: Sub title, name: subTitle, widget: string }
          - { label: Paragraph 1, name: paragraphOne, widget: text }
          - { label: Paragraph 2, name: paragraphTwo, widget: text }
      - label: "Testimonials"
        name: "testimonials"
        file: "src/_data/testimonials.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Sub Title, name: subTitle, widget: text }
          - label: Testimonial Items
            name: testimonialItems
            widget: list
            collapsed: false
            allow_add: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Quote, name: quote, widget: string }
              - { label: Name, name: name, widget: string }
      - label: "Disclaimer"
        name: "disclaimer"
        file: "src/_data/disclaimer.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Paragraph 1, name: paragraph1, widget: text }
          - { label: Paragraph 2, name: paragraph2, widget: text }
          - { label: Paragraph 3, name: paragraph3, widget: text }
          - { label: Paragraph 4, name: paragraph4, widget: text }

          
          
      
